apiVersion: v1
entries:
  kminion:
  - apiVersion: v2
    appVersion: v2.2.0
    created: "2022-07-28T12:05:25.760691015Z"
    description: A Helm chart to deploy KMinion - a Prometheus Exporter for Apache
      Kafka
    digest: 358bdd509f573049d4bfe77d2edb94c7ad3938f609aea11a8e2c2dc65cca2a9a
    name: kminion
    type: application
    urls:
    - kminion-0.9.0.tgz
    version: 0.9.0
  - apiVersion: v2
    appVersion: v2.2.0
    created: "2022-07-28T12:05:25.759924785Z"
    description: A Helm chart to deploy KMinion - a Prometheus Exporter for Apache
      Kafka
    digest: be8f0047b345d3954fc7c7e7f8953a848c909ef253107d6e77ed747843ddd167
    name: kminion
    type: application
    urls:
    - kminion-0.8.3.tgz
    version: 0.8.3
  - apiVersion: v2
    appVersion: v2.1.0
    created: "2022-07-28T12:05:25.759142155Z"
    description: A Helm chart to deploy KMinion - a Prometheus Exporter for Apache
      Kafka
    digest: 888bc665cddc6b6b99af1ce6dd1dea0b107a2e928dff6bfe1c077bc741e20ef7
    name: kminion
    type: application
    urls:
    - kminion-0.8.2.tgz
    version: 0.8.2
  - apiVersion: v2
    appVersion: v2.1.0
    created: "2022-07-28T12:05:25.758380525Z"
    description: A Helm chart to deploy KMinion - a Prometheus Exporter for Apache
      Kafka
    digest: e59c5d5574f162708bf1434c266acbfd9040a89aa7a4abd4a0db70885248e38d
    name: kminion
    type: application
    urls:
    - kminion-0.8.1.tgz
    version: 0.8.1
  - apiVersion: v2
    appVersion: v2.1.0
    created: "2022-07-28T12:05:25.757630796Z"
    description: A Helm chart to deploy KMinion - a Prometheus Exporter for Apache
      Kafka
    digest: f54d8236f8cf03c863b53e077e1647164ffe2a7c34e1cf77101fa3312c589706
    name: kminion
    type: application
    urls:
    - kminion-0.8.0.tgz
    version: 0.8.0
  - apiVersion: v2
    appVersion: v2.1.0
    created: "2022-07-28T12:05:25.756848565Z"
    description: A Helm chart to deploy KMinion - a Prometheus Exporter for Apache
      Kafka
    digest: 4cc64cd9f78bd55673b00612579157e493020fb76440abbef10fe5152aef9acc
    name: kminion
    type: application
    urls:
    - kminion-0.7.0.tgz
    version: 0.7.0
  - apiVersion: v2
    appVersion: v2.1.0
    created: "2022-07-28T12:05:25.756098036Z"
    description: A Helm chart to deploy KMinion - a Prometheus Exporter for Apache
      Kafka
    digest: 0955e04fe9ef4b516fb0d9ed439ae79778ccdffcf817f09099790cb7e183e4d4
    name: kminion
    type: application
    urls:
    - kminion-0.6.0.tgz
    version: 0.6.0
  - apiVersion: v2
    appVersion: v2.0.0
    created: "2022-07-28T12:05:25.755282904Z"
    description: A Helm chart to deploy KMinion - a Prometheus Exporter for Apache
      Kafka
    digest: d3eb64d05535e136802538662eef7e9fdfdb3f0b93b6a42dfdcc93ee7deeadbd
    name: kminion
    type: application
    urls:
    - kminion-0.5.0.tgz
    version: 0.5.0
  - apiVersion: v2
    appVersion: v2.0.0
    created: "2022-07-28T12:05:25.754560676Z"
    description: A Helm chart to deploy KMinion - a Prometheus Exporter for Apache
      Kafka
    digest: 6b4209352d1dffd7873791ee1573dc325eb08d67656b01b430729f45dea4c09a
    name: kminion
    type: application
    urls:
    - kminion-0.4.0.tgz
    version: 0.4.0
  - apiVersion: v2
    appVersion: v2.0.0
    created: "2022-07-28T12:05:25.753875149Z"
    description: A Helm chart to deploy KMinion - a Prometheus Exporter for Apache
      Kafka
    digest: c51e3b45791e9fd51f33036916b0d36f7ac695e2fa916a9e99882ea83914ed97
    name: kminion
    type: application
    urls:
    - kminion-0.3.1.tgz
    version: 0.3.1
  - apiVersion: v2
    appVersion: v2.0.0
    created: "2022-07-28T12:05:25.753186122Z"
    description: A Helm chart to deploy KMinion - a Prometheus Exporter for Apache
      Kafka
    digest: a2be2dd8a02dc5222ec7386195a0e25b2682a39bbdcf52b60793c171acac7653
    name: kminion
    type: application
    urls:
    - kminion-0.3.0.tgz
    version: 0.3.0
  - apiVersion: v2
    appVersion: v2.0.0
    created: "2022-07-28T12:05:25.752501795Z"
    description: A Helm chart to deploy KMinion - a Prometheus Exporter for Apache
      Kafka
    digest: 321b6d5ff95ce310d2a3257b3d55f9ced51de99af6519d6d91723d7bdb6456fa
    name: kminion
    type: application
    urls:
    - kminion-0.2.2.tgz
    version: 0.2.2
  - apiVersion: v2
    appVersion: v2.0.0
    created: "2022-07-28T12:05:25.751754666Z"
    description: A Helm chart to deploy KMinion - a Prometheus Exporter for Apache
      Kafka
    digest: ed57df27158521a1eb33d215731fcc3248c71b3f36a4a029eb2d3a7b617ca519
    name: kminion
    type: application
    urls:
    - kminion-0.2.1.tgz
    version: 0.2.1
  - apiVersion: v2
    appVersion: v2.0.0
    created: "2022-07-28T12:05:25.750723326Z"
    description: A Helm chart to deploy KMinion - a Prometheus Exporter for Apache
      Kafka
    digest: 025661ee7cc574ad8dde7a68093a3b614fc92e26dd5dd398fc89d0b5308010e1
    name: kminion
    type: application
    urls:
    - kminion-0.2.0.tgz
    version: 0.2.0
  - apiVersion: v2
    appVersion: v2.0.0
    created: "2022-07-28T12:05:25.749877493Z"
    description: A Helm chart to deploy KMinion - a Prometheus Exporter for Apache
      Kafka
    digest: e277e976d864b4bd2e505038dd865a9300486ae8c4323d3f0be40b84df75732b
    name: kminion
    type: application
    urls:
    - kminion-0.1.3.tgz
    version: 0.1.3
  - apiVersion: v2
    appVersion: v2.0.0
    created: "2022-07-28T12:05:25.749001258Z"
    description: A Helm chart to deploy KMinion - a Prometheus Exporter for Apache
      Kafka
    digest: 562937d3613624c55984e51adbc6765e7898d1cf8cc2d7d241b6d671bbc12303
    name: kminion
    type: application
    urls:
    - kminion-0.1.2.tgz
    version: 0.1.2
  - apiVersion: v2
    appVersion: v2.0.0
    created: "2022-07-28T12:05:25.747191988Z"
    description: A Helm chart to deploy KMinion - a Prometheus Exporter for Apache
      Kafka
    digest: 25e83d7c7cc92a63268d76b13ecc13077758b48be093490f281498a4f55ad3ca
    name: kminion
    type: application
    urls:
    - kminion-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v2
    appVersion: v2.0.0
    created: "2022-07-28T12:05:25.745481321Z"
    description: A Helm chart to deploy KMinion - a Prometheus Exporter for Apache
      Kafka
    digest: 7c10e9d9957e9752bc6f4b4a1fffb742d88cd57be06bf4f26ff7b5031645ccbd
    name: kminion
    type: application
    urls:
    - kminion-0.1.0.tgz
    version: 0.1.0
generated: "2022-07-28T12:05:25.744582686Z"
