apiVersion: v1
entries:
  kminion:
  - apiVersion: v2
    appVersion: v2.0.0
    created: "2021-03-15T09:51:48.778827194Z"
    description: A Helm chart to deploy KMinion - a Prometheus Exporter for Apache Kafka
    digest: 96a18f0e061920966116ba1cd0d04aa31f0dd57e27f079f0372fe8cbf7b711a3
    name: kminion
    type: application
    urls:
    - kminion-0.2.1.tgz
    version: 0.2.1
  - apiVersion: v2
    appVersion: v2.0.0
    created: "2021-03-15T09:51:48.77737621Z"
    description: A Helm chart to deploy KMinion - a Prometheus Exporter for Apache Kafka
    digest: 025661ee7cc574ad8dde7a68093a3b614fc92e26dd5dd398fc89d0b5308010e1
    name: kminion
    type: application
    urls:
    - kminion-0.2.0.tgz
    version: 0.2.0
  - apiVersion: v2
    appVersion: v2.0.0
    created: "2021-03-15T09:51:48.776133339Z"
    description: A Helm chart to deploy KMinion - a Prometheus Exporter for Apache Kafka
    digest: e277e976d864b4bd2e505038dd865a9300486ae8c4323d3f0be40b84df75732b
    name: kminion
    type: application
    urls:
    - kminion-0.1.3.tgz
    version: 0.1.3
  - apiVersion: v2
    appVersion: v2.0.0
    created: "2021-03-15T09:51:48.775535104Z"
    description: A Helm chart to deploy KMinion - a Prometheus Exporter for Apache Kafka
    digest: 562937d3613624c55984e51adbc6765e7898d1cf8cc2d7d241b6d671bbc12303
    name: kminion
    type: application
    urls:
    - kminion-0.1.2.tgz
    version: 0.1.2
  - apiVersion: v2
    appVersion: v2.0.0
    created: "2021-03-15T09:51:48.774955971Z"
    description: A Helm chart to deploy KMinion - a Prometheus Exporter for Apache Kafka
    digest: 25e83d7c7cc92a63268d76b13ecc13077758b48be093490f281498a4f55ad3ca
    name: kminion
    type: application
    urls:
    - kminion-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v2
    appVersion: v2.0.0
    created: "2021-03-15T09:51:48.774330334Z"
    description: A Helm chart to deploy KMinion - a Prometheus Exporter for Apache Kafka
    digest: 7c10e9d9957e9752bc6f4b4a1fffb742d88cd57be06bf4f26ff7b5031645ccbd
    name: kminion
    type: application
    urls:
    - kminion-0.1.0.tgz
    version: 0.1.0
generated: "2021-03-15T09:51:48.773477185Z"
