name: snyk scanning

on:
  push:
    branches: ["master", "v2*"]
	schedule:
		- cron: "0 0 * * *"

  workflow_dispatch:

jobs:
  snyk:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: install snyk
        run: npm install -g snyk

      - name: install deps and scan
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          snyk monitor --project-name=kminion --remote-repo=redpanda-data/kminion --target-reference=${GITHUB_REF#refs/heads/} .
        shell: bash